### ISSUE TITLE
FSYNC will add keyboard delay

### ISSUE THREAD

**Issue by gabriele2000** [Kron4ek/Wine-Builds#40] opened 2021-06-20 22:01 UTC
On high CPU-usage scenarios, enabling FSYNC will add a strange delay, basically you keep pressing W (for example) but when you stop wine will think that the key is still pressed, for a few second or just half a second... it's a bit randomic

**Comment by Kron4ek** [comment] 2021-06-21 09:10
I doubt i can help you with that since i'm not a Wine/fsync developer. Anyway, here are a few things that worth checking. Does this happen with older wine-tkg versions (6.8 and 6.9 at least)? Does this happen with Proton (Experimental and 6.3-4)? Does this happen with ESYNC?

You can use stress to get high CPU usage. For example: `stress -c 4` will fully load 4 CPU cores.

In addition, `WINEFSYNC_SPINCOUNT` env variable can make reproduction of the issue easier or harder. Afaik, the default spincount value is 100. Lower values should decrease cpu usage, while much higher values (1000, 5000, 10000 and so on)  will likely increase it. [In my experience](https://flightlessmango.com/games/15751/logs/783), very big values significantly reduce performance in CPU-limited scenarios.

**Comment by gabriele2000** [comment] 2021-06-21 11:02
> I doubt i can help you with that since i'm not a Wine/fsync developer. Anyway, here are a few things worth checking. Does this happen with older wine-tkg versions (6.8 and 6.9 at least)? Does this happen with Proton (Experimental and 6.3-4)? Does this happen with ESYNC?
> 
> You can use stress to get high CPU usage. For example: `stress -c 4` will fully load 4 CPU cores.
> 
> In addition, `WINEFSYNC_SPINCOUNT` env variable can make reproduction of the issue easier or harder. Afaik, the default spincount value is 100. Lower values should decrease cpu usage, while much higher values (1000, 5000, 10000 and so on) will likely increase it. [In my experience](https://flightlessmango.com/games/15751/logs/783), very big values significantly reduce performance in CPU-limited scenarios.

ESYNC has no problems... though I wonder: isn't FSYNC supposed to be better? It's worse in almost everything, as far as I'm seeing...

**Comment by Kron4ek** [comment] 2021-06-21 11:23
I beleive that depends on hardware. It's worse than ESYNC on my 2 core 4 threads CPU, but i guess it may be better on more powerful CPUs with more cores/threads.

There is also Futex2 which i haven't tested yet.

**Comment by gabriele2000** [comment] 2021-06-21 13:13
> I believe that depends on hardware. It's worse than ESYNC on my 2 core 4 threads CPU, but i guess it may be better on more powerful CPUs with more cores/threads.
> 
> There is also Futex2 which i haven't tested yet.

I've got an i7-7700HQ so 4 cores, 8 threads...
How can I enable futex2?

**Comment by Kron4ek** [comment] 2021-06-21 13:21
As far as i know it's enabled by default, but you need a custom kernel with futex2 support (for example, linux-zen and xanmod support it).

On wine-staging-tkg builds you will see `futex2: up and running.` if it's working.

**Comment by gabriele2000** [comment] 2021-06-21 13:24
> As far as i know it's enabled by default, but you need a custom kernel with futex2 support (for example, linux-zen and xanmod support it).
> 
> On wine-staging-tkg builds you will see `futex2: up and running.` if it's working.

I've got xanmod kernel but I don't see anything like this... maybe I need to set an env variable?

**Comment by Kron4ek** [comment] 2021-06-21 13:27
Try `WINEFSYNC_FUTEX2=1`, and maybe `WINEFSYNC` is also need to be enabled.

**Comment by gabriele2000** [comment] 2021-06-21 13:32
> As far as i know it's enabled by default, but you need a custom kernel with futex2 support (for example, linux-zen and xanmod support it).
> 
> On wine-staging-tkg builds you will see `futex2: up and running.` if it's working.

I've got xanmod kernel but I don't see anything like this... maybe I need to set an env variable?

**Comment by gabriele2000** [comment] 2021-06-21 13:38
> Try `WINEFSYNC_FUTEX2=1`, maybe `WINEFSYNC` is also need to be enabled.
> 
> And check if you have `CONFIG_FUTEX2` enabled in your kernel config and if `/sys/kernel/futex2` is present.

`/sys/kernel/futex2` doesn't exist, also where is the kernel config located?
xanmod has futex2 indeed, but I don't see it, strange

**Comment by Kron4ek** [comment] 2021-06-21 13:42
The kernel config should be in /boot or in /proc/config.gz (`zcat /proc/config.gz`), or in both locations.

What xanmod version are you using? 5.10 has no futex2 support, but 5.12 has.

**Comment by gabriele2000** [comment] 2021-06-21 13:44
> The kernel config should be in /boot or in /proc/config.gz (`zcat /proc/config.gz`), or in both locations.
> 
> What xanmod version are you using? 5.10 has no futex2 support, but 5.12 has.

Kernel version:
`5.12.12-xanmod1-cacule`

`CONFIG_FUTEX=y
CONFIG_FUTEX2=y
CONFIG_FUTEX_PI=y`

**Comment by Kron4ek** [comment] 2021-06-21 13:52
Well, although `CONFIG_FUTEX2` is enabled, but the fact that /sys/kernel/futex2 is missing means that Futex2 is not working.

I just tried linux-zen and there is `/sys/kernel/futex2` and wine-staging-tkg shows `futex2: up and running.` when i enable `WINEFSYNC` (enabling `WINEFSYNC_FUTEX2` is not needed).

**Comment by gabriele2000** [comment] 2021-06-21 13:56
> Well, although `CONFIG_FUTEX2` is enabled, but the fact that `/sys/kernel/futex2` is missing means that Futex2 is not working.
> 
> I just tried linux-zen and there is `/sys/kernel/futex2` and wine-staging-tkg shows `futex2: up and running.` when `WINEFSYNC` is enabled (enabling `WINEFSYNC_FUTEX2` is not needed).

damn, how can I install the missing module, if it's a module? I'm searching on google but I can't find anything

**Comment by Kron4ek** [comment] 2021-06-21 14:01
It's not an an external module, so the only option is to install kernel with properly enabled Futex2.

**Comment by Kron4ek** [comment] 2021-06-21 14:08
Try regular xanmod (I mean without cacule scheduler), maybe futex2 is working there. You can also manually compile you own kernel with futex2, [linux-tkg](https://github.com/Frogging-Family/linux-tkg) project allows to do this pretty easily.

**Comment by gabriele2000** [comment] 2021-06-21 14:18
> Try regular xanmod (I mean without cacule scheduler), maybe futex2 is working there. You can also manually compile your own kernel with futex2, [linux-tkg](https://github.com/Frogging-Family/linux-tkg) project allows to do this pretty easily.

even without cacule scheduler, futex2 isn't working... I'll switch again to cacule and I'll wait a response on the github thread that I opened, 'cuz the patch should be applied by default, as the homepage states

**Comment by gabriele2000** [comment] 2021-06-21 23:48
@Kron4ek [WHOAH! Look at that!](https://github.com/xanmod/linux/issues/161)

**Comment by gabriele2000** [comment] 2021-06-24 18:35
Futex2 didn't solve the problem, but now it's more bearable.
Loadings are even faster, slightly better FPS as far as I can see

**Comment by Kron4ek** [comment] 2021-06-24 19:00
Keep in mind that futex2 is still considered experimental and may cause issues in some games.

Closing this issue as i can't do anything about it anyway.

**Closed by Kron4ek** 2021-06-24 19:00 UTC

**Comment by BailShamber** [comment] 2021-06-26 06:47
@gabriele2000 try `export XMODIFIERS=@im=none` it has fixed this particular problem for me in the past.

**Comment by gabriele2000** [comment] 2021-06-26 18:43
> @gabriele2000 try `export XMODIFIERS=@im=none` it has fixed this particular problem for me in the past.

what does it do?

**Comment by BailShamber** [comment] 2021-06-26 22:29
@gabriele2000 It's an environment variable that has to do with the input method, I saw in a bug report that setting it gets rid of the stuck key effect in wine.

Source: https://bugzilla.redhat.com/show_bug.cgi?id=1279587#c21

**Comment by BailShamber** [comment] 2021-06-26 22:31
P.S The env variable is `XMODIFIERS` and it's value is `@im=none` the value kinda looks weird but that's what it is.

**Comment by lavyadrian** [comment] 2022-07-10 08:36
As of 2022 I am playing no man's sky and the keyboard delay bug is still very much present, so I don't know why no one is looking into it... I wanted to open an issue about it but there was already one AND it was closed even though the bug is still there...
Is there any chance the wine devs could do something abotu this? the XMODIFIERS env var did nothing for me, so here I am asking for help. I am using zorin os with kernel versio 5.18 and wine build 7.0.

**Comment by Kron4ek** [comment] 2022-07-10 08:52
Are you sure it's a Wine issue and not a game issue? Also, are you using Esync or Fsync or none?

**Comment by gabriele2000** [comment] 2022-07-10 13:52
> As of 2022 I am playing no man's sky and the keyboard delay bug is still very much present, so I don't know why no one is looking into it... I wanted to open an issue about it but there was already one AND it was closed even though the bug is still there... Is there any chance the wine devs could do something about this? the XMODIFIERS env var did nothing for me, so here I am asking for help. I am using zorin os with kernel version 5.18 and wine build 7.0.

This is what you want to insert in your .profile file in your home folder.
You can ignore what you don't want anyway.
After you put these lines in the end of the file, you write "source .profile" and you restart your PC.

`# WINE STUFF #
export WINEFSYNC=1
export WINE_FULLSCREEN_FSR=1
export WINE_LARGE_ADDRESS_AWARE=1
export DXVK_ENABLE_NVAPI=1
export DXVK_ASYNC=1
export __GL_THREADED_OPTIMIZATION=1
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
export XMODIFIERS=@im=none`

**Comment by lavyadrian** [comment] 2022-07-12 13:04
> 

I am playing original sin 2 and when you scroll the game screen with the keyboard, it will keep on scrolling for a bit when the key is released even though its not as bad as no mans sky, so maybe some games are VERY sensitive to what wine/fsync does, others (like doom eternal and control) does not have that problem.

**Comment by lavyadrian** [comment] 2022-07-12 13:07
> > As of 2022 I am playing no man's sky and the keyboard delay bug is still very much present, so I don't know why no one is looking into it... I wanted to open an issue about it but there was already one AND it was closed even though the bug is still there... Is there any chance the wine devs could do something about this? the XMODIFIERS env var did nothing for me, so here I am asking for help. I am using zorin os with kernel version 5.18 and wine build 7.0.
> 
> This is what you want to insert in your .profile file in your home folder. You can ignore what you don't want anyway. After you put these lines in the end of the file, you write "source .profile" and you restart your PC.
> 
> `# WINE STUFF #` `export WINEFSYNC=1` `export WINE_FULLSCREEN_FSR=1` `export WINE_LARGE_ADDRESS_AWARE=1` `export DXVK_ENABLE_NVAPI=1` `export DXVK_ASYNC=1` `export __GL_THREADED_OPTIMIZATION=1` `export __GL_SHADER_DISK_CACHE=1` `export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1` `export XMODIFIERS=@im=none`

I dont understand what do you mean by write source .profile? Also most of these options can be enabled through lutris right? What's the difference?

**Comment by gabriele2000** [comment] 2022-07-12 14:19
> > > As of 2022 I am playing no man's sky and the keyboard delay bug is still very much present, so I don't know why no one is looking into it... I wanted to open an issue about it but there was already one AND it was closed even though the bug is still there... Is there any chance the wine devs could do something about this? the XMODIFIERS env var did nothing for me, so here I am asking for help. I am using zorin os with kernel version 5.18 and wine build 7.0.
> > 
> > 
> > This is what you want to insert in your .profile file in your home folder. You can ignore what you don't want anyway. After you put these lines in the end of the file, you write "source .profile" and you restart your PC.
> > `# WINE STUFF #` `export WINEFSYNC=1` `export WINE_FULLSCREEN_FSR=1` `export WINE_LARGE_ADDRESS_AWARE=1` `export DXVK_ENABLE_NVAPI=1` `export DXVK_ASYNC=1` `export __GL_THREADED_OPTIMIZATION=1` `export __GL_SHADER_DISK_CACHE=1` `export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1` `export XMODIFIERS=@im=none`
> 
> I dont understand what do you mean by write source .profile? Also most of these options can be enabled through lutris right? What's the difference?

I don't have Lutris so I can't help you with this, anyway I can make a video... 

https://user-images.githubusercontent.com/12186181/178512240-bbca35bd-9e19-451d-a923-39e342f51116.mp4
